### ISSUE TITLE
[API] 일반 검색 API

### ISSUE THREAD

**Issue by dahyunko** [ASAC-marketplace/backend#12]
## ISSUE
(Board: 25)
키워드로 검색

## ESTIMATE
2D

## TASKS
- [ ] 검색 키워드를 요청, 관련 상품 처리
- [ ] 관련성, 인기, 판매량 등의 기준으로 정렬
- [ ] 페이지 별로 검색 결과 데이터 제공
- [ ] 페이징 처리된 검색 결과와 각 결과의 필요한 정보를 DTO 형태로 반환
