### ISSUE TITLE
[API] 급상승 검색어 API

### ISSUE THREAD

**Issue by dahyunko** [ASAC-marketplace/backend#14]
## ISSUE
(Board: 25)
급상승 검색어 데이터 수집, 반환

## ESTIMATE
2D
## TASKS
- [ ] 일정 기간 동안의 검색 빈도수가 급증한 검색어를 파악
- [ ] 검색 페이지 방문할 때
- [ ] 지정된 기간 동안 급증한 검색 빈도수를 기준으로 검색어를 선정
- [ ] 급상승 검색어 목록 반환
- [ ] 예시
GET /api/search/trending
Response:
{
  "trendingKeywords": [
    {"keyword": "keyword1", "frequency": 120},
    {"keyword": "keyword2", "frequency": 110},
    ...
  ]
}
