### ISSUE TITLE
[API] 상품설명 API

### ISSUE THREAD

**Issue by dahyunko** [ASAC-marketplace/backend#17]
## ISSUE
(Board : 27-28)
<좋아요>, <구매하기> 따로 API 개설
1) 개인별 상품 후기 : id, 상품명, 후기 제목, 후기 내용, 

## ESTIMATE
3D

## TASKS 
- [x] 상품 설명 정보 전송 로직 구현 / 반환(브랜드, 상품명, 상세 설명, 이미지URL 등..) 
- [x] <쿠폰받기> 로직 /쿠폰받기 버튼 클릭 / 쿠폰 발급 성공 또는 실패 메시지
- [x] 개인별 상품 후기 전송 로직 /반환 상품 후기 리스트
- [x] <도움돼요> 로직
