### ISSUE TITLE
[API] 회원 로그아웃 API

### ISSUE THREAD

**Issue by dahyunko** [ASAC-marketplace/backend#27]
## ISSUE
(Board : 52)

## TASKS
- [ ] 사이트 로그아웃 로직
- [ ] 요청: 사용자가 로그아웃 버튼 클릭
- [ ] 처리: 사용자의 현재 세션 또는 인증 토큰을 무효화
- [ ] 반환: 로그아웃 성공 여부 메시지
