### ISSUE TITLE
[API] 유저 정보 조회 API

### ISSUE THREAD

**Issue by aaronryu** [ASAC-marketplace/backend#4]
## ISSUE

유저 정보 조회 API - (1) JWT 헤더 기반 조회, (2) UserID 기반 조회

## ESTIMATE

**1d**

## TASKS
- [ ] Entity 연결 및 Repository 정의
- [ ] Service 와 DTO 정의
- [ ] Controller 생성 및 HandlerMapping

**Comment by aaronryu** [comment]
작업하다가 너무 어려워요 도움이 필요합니다. @aaronryu 살려주세요.

**Comment by aaronryu** [comment]
그러면 이 티켓 제가 가져다가 수행할테니까, 작업하시던 브랜치 알려주시고, 제가 하고있던 티켓 .... 작업 가져가주심되어요.
꼭 잊지마시고 Assigned 세나 아이디로 변경 후 작업 부탁드립니다.
