### ISSUE TITLE
[API] 메인 마감세일 API

### ISSUE THREAD

**Issue by dahyunko** [ASAC-marketplace/backend#9]
## ISSUE
(Board: 24)
메인화면 마감세일 상품 데이터 페이징 후 반환
## ESTIMATE
1d
## TASKS
- [ ] 마감세일 해당 상품 검색 /페이지 번호, 페이지당 상품 수? /
- [ ] 할인율 적용 로직 
- [ ] **기준으로 정렬 마감시간 할인율 등
- [ ] 페이징 후 필요한 데이터 DTO로 반환
